import "./globals.css";
import type { GetServerSidePropsContext, Metadata } from "next";
import Navbar from "@/components/Navbar";
import Provider from "../components/Provider";
import { Session } from "next-auth";
import RecoilContextProvider from "../components/recoilContextProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode;
  session: Session;
}) {
  return (
    <html lang="en">
      <body>
        <Provider session={session}>
          <Navbar />
          <RecoilContextProvider>{children}</RecoilContextProvider>
        </Provider>
      </body>
    </html>
  );
}
